module.exports = {
    AUTO_VIEW_STATUS: 'true',
    AUTO_LIKE_STATUS: 'true',
    AUTO_RECORDING: 'true',
    AUTO_LIKE_EMOJI: ['🌸', '🪴', '💫', '🍂', '🌟','🫀', '👀', '🤖', '🚩', '🥰', '🗿', '💜', '💙', '🌝', '🖤', '💚'],
    PREFIX: '.',
    MAX_RETRIES: 3,
    GROUP_INVITE_LINK: 'https://whatsapp.com/channel/0029Vb75RsG9Gv7Lr28vn92O',
    ADMIN_LIST_PATH: './admin.json',
    IMAGE_PATH: 'https://files.catbox.moe/jojm9q.png',
    NEWSLETTER_JID: '120363424231270188@newsletter',
    NEWSLETTER_MESSAGE_ID: '428',
    OTP_EXPIRY: 300000,
    NEWS_JSON_URL: '',
    BOT_NAME: 'SHAHBAZ-MINI',
    OWNER_NAME: 'MR SHAHBAZ',
    OWNER_NUMBER: '923191285720',
    BOT_VERSION: '1.0.0',
    BOT_FOOTER: '> ᴘᴏᴡᴇʀᴇᴅ ʙʏ SHAHBAZ ᴛᴇᴄʜ',
    CHANNEL_LINK: 'https://whatsapp.com/channel/0029Vb75RsG9Gv7Lr28vn92O',
};
